### ISSUE TITLE
'cross-device link not permitted' Error on windows

### ISSUE THREAD

**Issue by uwascan** [arboleya/electrify#26]
I get the above mentioned error on windows when I run

```
electrify package

```

but running

```
electrify

```

builds and runs my app in electron

The info below might help. How do I fix this. 

```
D:\PROJECTS\METEOR\Aurelia\aurelia-meteor-todos-master>electrify package
INFO  electrify:index:  initializing
=====================================
{
  "version": "2.0.2",
  "running_through_cli": true,
  "is_development_mode": false,
  "is_running_tests": false,
  "stdio": "inherit",
  "sys": {
    "platform": "win32",
    "arch": "x64",
    "is_windows": true,
    "is_linux": false,
    "is_osx": false
  },
  "os": {
    "name": "win32",
    "home": "C:\\Users\\UWASCAN",
    "tmp": "C:\\Users\\UWASCAN\\AppData\\Local\\Temp"
  },
  "app": {
    "root": "D:\\PROJECTS\\METEOR\\Aurelia\\aurelia-meteor-todos-master\\.electrify",
    "meteor": "D:\\PROJECTS\\METEOR\\Aurelia\\aurelia-meteor-todos-master",
    "is_packaged": false,
    "isnt_packaged": true,
    "bin": "D:\\PROJECTS\\METEOR\\Aurelia\\aurelia-meteor-todos-master\\.electrify\\bin",
    "dist": "D:\\PROJECTS\\METEOR\\Aurelia\\aurelia-meteor-todos-master\\.electrify\\.dist",
    "config_path": "D:\\PROJECTS\\METEOR\\Aurelia\\aurelia-meteor-todos-master\\.electrify\\electrify.json",
    "settings": {}
  },
  "core": {
    "tmp": "C:\\Users\\UWASCAN\\AppData\\Local\\Temp\\electrify",
    "root": "C:\\Users\\UWASCAN\\AppData\\Local\\Temp\\electrify\\core"
  },
  "meteor": {
    "root": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\meteor.bat",
    "tools": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\",
    "dev_bundle": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle",
    "server_lib": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\server-lib",
    "server_modules": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\server-lib\\node_modules",
    "node_mods": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules",
    "node": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe",
    "npm": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js",
    "mongo": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\mongodb\\bin\\mongo.exe",
    "mongod": "C:\\Users\\UWASCAN\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.10\\mt-os.windows.x86_32\\dev_bundle\\mongodb\\bin\\mongod.exe"
  }
}
====================================
INFO  electrify:plugins:  use  mongodb
INFO  electrify:plugins:  use  nodejs
INFO  electrify:plugins:  use  socket
INFO  electrify:app:  bundling app
INFO  electrify:scaffold:  ensuring basic structure
INFO  electrify:plugins:  ensuring electrify dependencies
npm WARN package.json my-electrified-app@ No description
npm WARN package.json my-electrified-app@ No repository field.
npm WARN package.json my-electrified-app@ No README data
INFO  electrify:plugins:  load configured plugins []
INFO  electrify:plugins:  acquire
INFO  electrify:plugins:mongodb:  mongo already acquired, moving on
INFO  electrify:plugins:mongodb:  mongod already acquired, moving on
INFO  electrify:plugins:nodejs:  nodejs already acquired, moving on
INFO  electrify:plugins:socket:  nothing to acquire, skipping
INFO  electrify:app:  bundling meteor

WARNING: The output directory is under your source tree.

Message: Using Systemjs Loader...
Message: Using Aurelia Framework...
shell.js: internal error
Error: EXDEV, cross-device link not permitted 'C:\Users\UWASCAN\AppData\Local\Temp\electrify\bundling\bundle'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at D:\PROJECTS\METEOR\Aurelia\aurelia-meteor-todos-master\.electrify\node_modules\electrify\node_modules\shelljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (D:\PROJECTS\METEOR\Aurelia\aurelia-meteor-todos-master\.electrify\node_modules\electrify\node_modules\shelljs\src\mv.js:53:11)
    at Object.mv (D:\PROJECTS\METEOR\Aurelia\aurelia-meteor-todos-master\.electrify\node_modules\electrify\node_modules\shelljs\src\common.js:186:23)
    at ChildProcess.<anonymous> (D:\PROJECTS\METEOR\Aurelia\aurelia-meteor-todos-master\.electrify\node_modules\electrify\lib\app.js:134:11)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

**Comment by arboleya** [comment]
Hi, it seems this is a windows related question, nothing to do with Electrify.

Check this out: https://github.com/arboleya/electrify/issues/22
