### ISSUE TITLE
Problem with running on Windows 10 64 bit

### ISSUE THREAD

**Issue by iamgmd** [arboleya/electrify#33]
INFO  electrify:index:  initializing
path.js:9
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:9:11)
    at win32.join (path.js:222:5)
    at new Env (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\lib\env.js:115:23)
    at module.exports (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\lib\env.js:6:10)
    at new Electrify (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\lib\index.js:16:30)
    at module.exports (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\lib\index.js:5:10)
    at electrify (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\bin\cli.js:148:23)
    at Command.run (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\bin\cli.js:96:5)
    at Command.listener (C:\Users\geoff\AppData\Roaming\npm\node_modules\electrify\node_modules\commander\inde
x.js:301:8)
    at emitTwo (events.js:88:13)

I have tried to run this on two separate machines and get the same problem.

meteor create --example leaderboard
cd leaderboard
meteor add arboleya:electrify
electrify

This works perfectly on a mac, it's just Windows 10 that I am having this problem. If I run meteor inside the leaderboard directory, I get:-

=> Started proxy.
=> Started MongoDB.
I20151213-10:19:03.500(0)? electrify:meteor:index@server: cannot initialize connection. Did you `npm install -g electrify`?
I20151213-10:19:03.512(0)? install it and try running your meteor app with `electrify` npm command
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

I did perform 'npm install -g electrify' and can confirm that it can be reached on the command line.

**Comment by arboleya** [comment]
What version are you using?

`electrify -V`
`meteor version`

**Comment by sophiabersani** [comment]
Having this same issue.
Electrify 2.1.3
Meteor 1.2.1

**Comment by arboleya** [comment]
@iamgmd @gbersani  Found the problem, should release the fix tomorrow.

Tks for reporting.

**Comment by arboleya** [comment]
@gbersani @iamgmd Fixed in last version `2.1.4`.

**Comment by iamgmd** [comment]
@arboleya Many thanks, can confirm it works as expected. Keep up the good work!
