### ISSUE TITLE
error being thrown if the meteor check package is installed on method call to 'electrify.get.socket.port'

### ISSUE THREAD

**Issue by iamgmd** [arboleya/electrify#34]
I20151216-15:45:48.489(0)? Exception while invoking method 'electrify.get.socket.por
t' Error: Did not check() all arguments during call to 'electrify.get.socket.port'
I20151216-15:45:48.489(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHa
veBeenChecked (packages/check/match.js:411:1)
I20151216-15:45:48.489(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (pac
kages/check/match.js:106:1)
I20151216-15:45:48.489(0)?     at maybeAuditArgumentChecks (livedata_server.js:1695:
18)
I20151216-15:45:48.489(0)?     at livedata_server.js:708:19
I20151216-15:45:48.489(0)?     at [object Object]._.extend.withValue (packages/meteo
r/dynamics_nodejs.js:56:1)
I20151216-15:45:48.489(0)?     at livedata_server.js:706:40
I20151216-15:45:48.490(0)?     at [object Object]._.extend.withValue (packages/meteo
r/dynamics_nodejs.js:56:1)
I20151216-15:45:48.490(0)?     at livedata_server.js:704:46
I20151216-15:45:48.490(0)?     at tryCallTwo (C:\Users\Geoff Davis\AppData\Local.me
teor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib
\core.js:45:5)
I20151216-15:45:48.490(0)?     at doResolve (C:\Users\Geoff Davis\AppData\Local.met
eor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\
core.js:171:13)

Electrify: 2.1.4
Meteor: 1.2.1

**Comment by arboleya** [comment]
Good to know @iamgmd , I'm gonna address this in next release.

Perhaps these methods will be stripped out from the core anyway.

Thanks :beers:

**Comment by LeapingZ** [comment]
I20180707-14:28:00.263(-4)? electrify:meteor:index@server: connection is open
I20180707-14:28:04.137(-4)? Exception while invoking method 'electrify.get.socket.port' Error: Did not check() all arguments during call to 'electrify.get.socket.port'
I20180707-14:28:04.138(-4)?     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:515:13)
I20180707-14:28:04.138(-4)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:122:16)
I20180707-14:28:04.138(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
I20180707-14:28:04.138(-4)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180707-14:28:04.139(-4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180707-14:28:04.139(-4)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180707-14:28:04.139(-4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180707-14:28:04.139(-4)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180707-14:28:04.139(-4)?     at new Promise (<anonymous>)
I20180707-14:28:04.140(-4)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180707-14:28:04.140(-4)?     at packages/ddp-server/livedata_server.js:559:43
