### ISSUE TITLE
Error in Windows 'While loading plugin `compileNGScript` from package `pbastowski:angular-babel`'

### ISSUE THREAD

**Issue by lorenzogm** [arboleya/electrify#40]
The app works running 'meteor'. However, if I install electrify with 'npm install -g electrify' and then I run 'electrify' to get the following error:

```
Your app is crashing. Here's the latest log:
Started MongoDB.
Errors prevented startup:

While loading plugin `compileNGScript` from package `pbastowski:angular-babel`:
C:\Users\4379\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:34:13: Surprising path: /home/4379/data/projects/03_pricing-calculator/src/babel.json
  at toDosPath (C:\Users\4379\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:34:13)
  at Object.convertToOSPath (C:\Users\4379\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:47:12)
  at Object.wrapper (C:\tools\fs\files.js:1310:25)
  at getCustomConfig (packages/compileNGScript/plugin/ng-script-compiler.js:145:1)
  at Package (packages/compileNGScript/plugin/ng-script-compiler.js:27:1)
  at <runJavaScript-73>:170:4
  at <runJavaScript-73>:177:3


Your application has errors. Waiting for file change.
```

**Comment by lorenzogm** [comment]
Looks like it doesn't work on cygwin. I run it on windows cmd and it works.

However I get this error when I run 'electroify package':

```
D:\projects\03_pricing-calculator\src>electrify package
INFO  electrify:index:  initializing
INFO  electrify:plugins:  use  mongodb
INFO  electrify:plugins:  use  nodejs
INFO  electrify:plugins:  use  socket
INFO  electrify:app:  bundling app
INFO  electrify:scaffold:  ensuring basic structure
INFO  electrify:plugins:  ensuring electrify dependencies
INFO  electrify:plugins:  load configured plugins []
INFO  electrify:plugins:  acquire
INFO  electrify:plugins:mongodb:  mongo already acquired, moving on
INFO  electrify:plugins:mongodb:  mongod already acquired, moving on
INFO  electrify:plugins:nodejs:  nodejs already acquired, moving on
INFO  electrify:plugins:socket:  nothing to acquire, skipping
INFO  electrify:app:  bundling meteor
shell.js: internal error
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\4379\AppData\Loc
al\Temp\electrify\bundling\bundle' -> 'D:\projects\03_pricing-calculator\src\.el
ectrify\app'
    at Error (native)
    at Object.fs.renameSync (fs.js:729:18)
    at C:\Users\4379\AppData\Roaming\npm\node_modules\electrify\node_modules\she
lljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (C:\Users\4379\AppData\Roaming\npm\node_modules\electrify\node
_modules\shelljs\src\mv.js:53:11)
    at Object.mv (C:\Users\4379\AppData\Roaming\npm\node_modules\electrify\node_
modules\shelljs\src\common.js:186:23)
    at ChildProcess.<anonymous> (C:\Users\4379\AppData\Roaming\npm\node_modules\
electrify\lib\app.js:140:11)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Any idea about that?

```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\4379\AppData\Loc
al\Temp\electrify\bundling\bundle' -> 'D:\projects\03_pricing-calculator\src\.el
ectrify\app
```

**Comment by bcoutre** [comment]
Have you tried to move your project on C drive ?
cf.  https://github.com/arboleya/electrify/issues/22

**Comment by lorenzogm** [comment]
Thanks @bcoutre, this issue was fixed a long time ago. I think #22 was the solution.
