### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by paralin** [arboleya/electrify#57]
Apparently there are some critical fixes in newer versions of the deps, can we update electrify with newer deps?

**Comment by HZSamir** [comment]
Given that the author of this package seems to have properly disappeared, I have taken it upon myself to update the deps. They are available at NPM - Just try `npm i -g electrify-updated-test`. Whenever the author returns to us and proceeds to update this himself I'll take it down.

**Comment by cosmin-novac** [comment]
What are the advantages over the old deps?

**Comment by HZSamir** [comment]
@tenshis Basically everything new with Electron and Electron-Packager. You should check the release history of both to know for sure.

**Comment by yjose** [comment]
hi I use   npm i -g electrify-updated-test to update electrify dependencies and i have this problem 
`  C:\Users\Youssouf\AppData\Local.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules
INFO  electrify:electron:  packaging "my-electrified-app" for platform win32-x64 using electron v1.3.5
x64
win32

C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\get-package-info\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^
 Error: Cannot find module 'package.json' from 'C:\Users\Youssouf\Documents'
    at C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Youssouf\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)`

thank you to help me to resolve my problem

**Comment by mertyildiran** [comment]
@Unforgiven-wanda I'm getting a lot of errors when I use your `eletrify-updated-test` package:

```
Uncaught Error: Cannot find module 'jquery'
global-imports.js:11 Uncaught TypeError: Cannot read property 'Materialize' of undefined
app.js:1 Uncaught ReferenceError: meteorInstall is not defined
lolcation.js:46 electrify:meteor:index@client: connection is open
lolcation.js:46 Uncaught ReferenceError: _ is not defined
```

Also I tried to upgrade to `"electron-prebuilt": "^1.4.0",` and `"electron-prebuilt": "^1.4.8",` same result. Do you have any idea?

**Comment by HZSamir** [comment]
@mertyildiran Some user reported that the Materialize package of Meteor is pretty much broken and thus should be avoided. See getmdl as replacement for instance.
As for Jquery it has never played well with Meteor as well, and I believe this is your issue [here](http://stackoverflow.com/questions/31504801/jquery-is-not-defined-in-meteor-app)

**Comment by mertyildiran** [comment]
@Unforgiven-wanda hmm, thanks a lot!
