### ISSUE TITLE
Dependencies path length too long in Windows

### ISSUE THREAD

**Issue by cosmin-novac** [arboleya/electrify#60]
When I electrify a project the node module dependencies generate a path that is too long for windows to read. 

How can I flatten my dependency path in an electrified package? Also, I heard this should be fixed in npm 3?

**Comment by cosmin-novac** [comment]
I found the answer - update both the electrify dependencies and meteor's npm. For posterity, these are the required steps:

1) meteor npm install -g npm@3 (deep dependency problem has been fixed with npm v 3)

2) meteor remove arboleya:electrify

3) npm install -g electrify-updated-test

4) remove any node_modules folder from your project + .electrify folder

5) meteor update  (updates to 1.3.5.1 - the deep dependency problem has been fixed since 1.3.4)

6) electrify package

**Comment by XaBerr** [comment]
@tenshis 
I follow your steps from 1-5, then I try `electrify` but I got this error:

```
C:\wamp\www\JUICE\projects\SPORE\meteorApp (master) (meteorApp@0.0.1)
λ electrify
[[[ electron C:\wamp\www\JUICE\projects\SPORE\meteorApp\.electrify` ]]]

App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\fede\AppData\Roaming\npm\node_modules\electrify-updated-test\node_modules\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp\www\JUICE\projects\SPORE\meteorApp\.electrify\index.js:1:96)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

In point 4) I manualy clear the folder `electrify/node_modules,` right?
