### ISSUE TITLE
Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Local\Temp\electrify\package' -> 'C:\appname\.electrify\.dist'

### ISSUE THREAD

**Issue by iaroshvictor** [arboleya/electrify#75]
I get allways this error on windows 10 x64 whn running electrify package
Error: EPERM: operation not permitted, rename 'C:\Users\Design\AppData\Local\Temp\electrify\package' -> 'C:\NoteApp\.electrify\.dist'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\shelljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\shelljs\src\mv.js:53:11)
    at Object.mv (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\shelljs\src\common.js:186:23)
    at C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\lib\electron.js:58:11
    at C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\electron-packager\index.js:198:7
    at end (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\run-series\index.js:8:15)
    at done (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\run-series\index.js:11:10)
    at each (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\run-series\index.js:16:43)
    at C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\electron-packager\common.js:129:7
    at end (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\run-series\index.js:8:15)
    at done (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\run-series\index.js:11:10)
    at each (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\run-series\index.js:16:43)
    at cb (C:\Users\Design\AppData\Roaming\npm\node_modules\electrify\node_modules\ncp\lib\ncp.js:255:37)

**Comment by lacymorrow** [comment]
Same ^
Had success packaging for OSX and Linux, no luck on windows.
Thought it could be the way slashes are escaped and tried to account for those tool
